### ISSUE TITLE
Seek information regarding the input parameters for the test setting

### ISSUE THREAD

**Issue by kulsingh** [ContextScout/ned-graphs#2]
We seek information from your side to understand what are the input parameters in the test phase of the model: 

1. Let's assume we have an input sentence "Michelle is walking on the street". Michelle is the surface form which has Its correct Wikidata ID is Q13133 (Michelle Obama)
2. while you test the model on the test set, what is the input? Do you just pass the sentence "Michelle is walking on the street" and directly predict its correct Wikidata Q id? Or you pass the sentence "Michelle is walking on the street" and also assume that Michelle as the recognized entity and pass sentence plus "Michelle" surface form as input and predicts the correct Wikidata ID? 
We are a bit confused about the input values for the test cases. For the training, it is quite clear.

**Comment by fractalego** [comment]
Hi, I'm not sure if I understand the question. We use the same format for training and testing. 
When testing we still have two wikidata items, one correct and one incorrect. For each option the system tries to predict whether the entity should be linked or not.

**Comment by kulsingh** [comment]
Thank you for the input. Your input is what I expected. thank you again.
