### ISSUE TITLE
Cannot reproduce results as mentioned in paper

### ISSUE THREAD

**Issue by chaitaliprabhu** [ContextScout/ned-graphs#3]
I am unable to reproduce the results as mentioned in your paper on the same dataset, code and embeddings.
I have followed the exact steps mentioned in the readme and run the model "wikidata_entity_linking_with_attentive_rnn_triplets". 
I haven't made any changes in the code and am using glove embeddings as mentioned, still the results do not match. 
Kindly look into the issue.

**Comment by chaitaliprabhu** [comment]
Final results on test data
precision 0.9832146490335707
recall 0.992299794661191
f1 0.9877363311190598

**Comment by fractalego** [comment]
Hi! These results are about 10% better than the state of the art, I do not feel they are accurate. Are you sure you didn't use the train set for testing purposes?

**Comment by chaitaliprabhu** [comment]
Hey ! Thanks for responding.
 No, I haven't made any changes. The test.py file uses '...test.json' file only

**Comment by fractalego** [comment]
This is very bizarre and I have no good explanation for it. The results are simply too good to be true.
Was there any error message? Maybe the system only runs for a subset of the test set.

**Comment by chaitaliprabhu** [comment]
That is what I think too. During training and testing there are a lot of exceptions (Expecting value: line 1 column 1 (char 0)) while reading data.

**Comment by fractalego** [comment]
I am not sure if I can help from here. Sometimes it is difficult to port a solution to other machines. It could be down to many factors. My advice would be to try to understand why this exception pops up. 

I am sorry but short of doing a pair programming session I am not able to correct this issue.

**Comment by iurshina** [comment]
I had the same issue and the same error (Expecting value: line 1 column 1 (char 0)). In my case, It was 429 (too many requests) error on sending requests to WikiData API. 

Adding User-Agent header helped. https://www.mediawiki.org/wiki/Wikidata_Query_Service/User_Manual#Query_limits

**Comment by fractalego** [comment]
Ah thank you! The API probably changed a bit after we published
