### ISSUE TITLE
Have problem

### ISSUE THREAD

**Issue by nicejava** [ContextScout/ned-graphs#4]
I following 
cd data
bunzip2 x*
cat x* > wikidata_items.csv
cd ..
after have wikidata_items.csv i try run train.py but have error below

![image](https://user-images.githubusercontent.com/6760497/134362945-c623a926-1332-4ada-a553-2dbd309b9e85.png)

what happen ?
thank you

**Comment by fractalego** [comment]
Hello! Thank you for your message. We cannot help you with installation issues (this is not a commercial project).
My personal advice is to look into the file that is not loading properly. I suspect some issue with the Linux/Windows format when it comes to the end-of-line ('\n' under Linux, '\n\r' under Windows).
