### ISSUE TITLE
Have probrem ..

### ISSUE THREAD

**Issue by nicejava** [ContextScout/ned-graphs#5]
i use library this 

tensorflow 1.13.2 
transformers==4.10.2
tensorflow==1.13.2
spacy==2.2.4
gensim==3.8.1

run in colab
when run train.py have error response like this , What happen ?

![image](https://user-images.githubusercontent.com/6760497/136699739-82dd863c-1555-4dd9-b524-360b9909b27c.png)

.. Thank you

**Comment by fractalego** [comment]
Hi! Out code is distributed as it is and we cannot help you debug your code. My advice would be to run it on a machine with more memory, as the error message implies.
