### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nicejava** [ContextScout/ned-graphs#6]
![image](https://user-images.githubusercontent.com/6760497/139572401-eb3cbfd7-90a6-41ee-acb4-ae1767a27f0e.png)

Have response like this and not have trained file ( Run in colab ) what happen ?
thank you

**Comment by fractalego** [comment]
Hi! Out code is distributed as it is and we cannot help you debug your code. My advice would be to run it on a machine with more memory, as the error message implies.
